#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
# # Dont Allow to push to main branch
# if [ $current_branch = "main" ]; then
#   echo "You can't push to the main branch!"
#   exit 1
# fi


npm run lint-fix:scripts
npm run lint-fix:styles
npm test
