#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

# echo "Running pre-commit script"

# echo "Current branch: $current_branch"

# # Dont Allow to commit to main branch
# if [ $current_branch = "main" ]; then
#   # Echo in red
#   echo "You can't commit to the main branch!"
#   exit 1
# fi

npx lint-staged
